// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220317145639_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "2044-et írunk, és a valóság elég ronda egy hely. Az emberiség nagy részéhez hasonlóan a gimnazista Wade Watts is azt a kiutat látja zord környezetéből, hogy bejelentkezik az OASIS-ba, a világméretű virtuális utópiába, ahol az avatárján keresztül mindenki szabadon tanulhat, dolgozhat, és szórakozhat. Ugyancsak az emberiség nagy részéhez hasonlóan Wade is arról álmodozik, hogy ő találja meg elsőként a virtuális világ elrejtett kincsét. A szimuláció tervezőjeként ismert James Halliday ugyanis ördögi feladványt hagyott maga után, amelynek leggyorsabb megfejtője szédületes vagyonra és hatalomra tehet szert.A Halliday által kifundált feladatok sikeres teljesítéséhez a popkultúra megszállott ismeretére van szükség, Wade pedig éppúgy otthon van a Gyalog galoppban, mint a Pac-Manben, a Rush életművében vagy az animékben. Amikor a tizennyolc éves srác hosszú évek kitartó munkája után megoldja az első feladványt, hirtelen a figyelem középpontjába kerül, és ez életveszélybe sodorja. Egyes játékosok ugyanis még a gyilkosságig is hajlandóak elmenni a mesés nyeremény megszerzéséért.",
                            ImageUrl = "https://s06.static.libri.hu/cover/e2/7/2625545_5.jpg",
                            Price = 9.99m,
                            Title = "Ready Player One"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Az 1984 (eredeti címén Nineteen Eighty-Four) egy szatirikus politikai regény és szerelmi történet George Orwelltől. Olyan disztópia (negatív utópia), amelyben a felügyelő állam tökéletes alkalmazkodást követel a polgároktól hazugságokkal, félelemkeltéssel és kegyetlen büntetésekkel. Az 1949-ben kiadott mű Orwell legnépszerűbb munkája, és az „orwelli” jelzőt ennek világára használjuk. Sok nyelvre lefordították; magyarul először a „Magyar Október” Szabadsajtó nevű szamizdatkiadó adta ki Antal György fordításában, 1984-ben, majd Szíjgyártó László fordításában az újvidéki Forum Könyvkiadónál 1986-ban, az Európa Könyvkiadónál pedig 1989-ben.",
                            ImageUrl = "https://s03.static.libri.hu/cover/a2/b/6051555_5.jpg",
                            Price = 12.99m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A Galaxis útikalauz stopposoknak című sorozatot (eredeti angol címén The Hitchhiker’s Guide to the Galaxy) először Douglas Adams rádiójátékaként ismerte meg a közönség, amelyet 1978-ban a BBC 4 rádió sugárzott fejezetenkénti folytatásokban. 1979 és 1992 között Adams ötrészes regényfolyamot írt, majd 2009-ben kiadták az Eoin Colfer által írt hatodik részt. 1981-ben televíziós sorozat, 1984-ben számítógépes játék, 1993 és 1996 között képregény és 2005-ben mozifilm is készült belőle, melynek forgatókönyvírója és egyik producere maga Douglas Adams volt. 2004–2005 folyamán a regény 3., 4. és 5. részének története alapján The Hitchhiker's Guide to the Galaxy Tertiary to Quintessential Phases címmel egy újabb, 14 részes rádiójátékot sugárzott a BBC 4. A sikeres regénysorozatot több mint harminc nyelvre fordították le,[1] lemez, kazetta és CD formátumban is kiadták, valamint színházi előadásként is látható volt.",
                            ImageUrl = "https://book24.hu/img/boritok/Gabo/9789635661251.jpg",
                            Price = 14.99m,
                            Title = "Galaxis útikalauz stopposoknak"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
